### ISSUE TITLE
CRUD para vídeos

### ISSUE THREAD

**Issue by Gabrielle-Ribeiro** [Gabrielle-Ribeiro/aluraflix#1]
**Descrição**
Criação de um CRUD para vídeos.

**Tasks**
- [x] Armazenar no banco de dados as seguintes informações sobre os vídeos: _id, titulo, descricao, url._
    - [x] Todos os campos de vídeos devem ser obrigatórios e validados.
- [x] Atender uma requisição GET que exiba todos os vídeos com o seguinte endpoint: `/videos`
- [x] Atender uma requisição GET que retorne um único vídeo, caso o ID do vídeo seja válido, com o seguinte endpoint: `/videos/1`
    - [x] Caso o vídeo não esteja cadastrado, retornar uma mensagem de **Não encontrado**.
- [x] Atender uma requisição POST que crie um novo vídeo, caso todos os campos estejam preenchidos e validados. (Retornar um Json com informações do vídeo criado.)
- [x] Atender uma requisição capaz de atualizar um ou mais campos de um vídeo. (Retornar um Json com informações do filme atualizado.)
- [x] Atender uma requisição capaz de deletar um vídeo pelo ID, como mostra o endpoint de exemplo: `videos/1`. (Retornar uma mensagem de sucesso ou falha.)
