### ISSUE TITLE
CRUD Categoria

### ISSUE THREAD

**Issue by Gabrielle-Ribeiro** [Gabrielle-Ribeiro/aluraflix#3]
**Descrição:** Criação de CRUD para categoria

**Tasks**
- [ ] Armazenar no banco de dados as seguintes informações sobre categorias: _id, titulo, cor_
- [ ] Atender uma requisição GET que exiba todos as categorias com o seguinte endpoint: `/categorias/`
- [ ] Atender uma requisição GET que retorne uma única categoria caso o ID do seja válido, com o seguinte endpoint: `/categorias/1/`
   - [ ] Caso a categoria não esteja cadastrada, retornar uma mensagem de **Não encontrado**.
- [ ] Atender uma requisição POST que crie uma nova categoria, caso todos os campos estejam preenchidos e validados. (Retornar um Json com informações da categoria criada.)
- [ ] Atender uma requisição capaz de atualizar um ou mais campos de uma categoria. (Retornar um Json com informações da categoria.) 
- [ ] Atender uma requisição capaz de deletar uma categoria pelo ID, como mostra o endpoint de exemplo: `categorias/1/`. (Retornar uma mensagem de sucesso ou falha.)
- [ ] A categoria com ID = 1, deve chamar LIVRE.
- [ ] Uma nova categoria não pode ser criada caso tenha algum campo vazio.
