### ISSUE TITLE
Agrupar vídeos e categorias

### ISSUE THREAD

**Issue by Gabrielle-Ribeiro** [Gabrielle-Ribeiro/aluraflix#4]
**Descrição**
Criação de uma relação entre vídeos e categorias

**Tasks**
- [ ] Implemente uma relação entre vídeos e categorias, atribuindo para cada vídeo uma categoria
- [ ] Caso a categoria não seja especificada na criação do vídeo, vamos atribuir o ID = 1.
- [ ] Criar uma rota GET relacionando categorias e videos. `categorias/:id/videos/`
